### ISSUE TITLE
Spinner causes tilt of the entire aircraft

### ISSUE THREAD

**Issue by MikhailChertkov** [ConstantDust/VS_tournament-Vintage#5]
Spinner causes tilt on 100% symmetrical planes. If u place left-rotating spinner aka propeller, the plane ll tilt right. And the same with right-rotating spinner. It causes left tilt. It makes planes uncontrollable sometimes. I can send video/photo bug capture via discord if is necessary.

**Comment by SuperCraftAlex** [comment]
thats not a tournament bug, thats vs2

solution:
make two propellers in front of each other, one of them rotates the other direction

issue closed

**Comment by MikhailChertkov** [comment]
Thank you so much!

**Comment by Derpxderp999** [comment]
It's kinda realistic.
